# Generated by Django 5.0.4 on 2024-07-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_fname', models.CharField(max_length=50)),
                ('user_lname', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=1500)),
                ('user_DOB', models.DateField()),
                ('user_phone', models.IntegerField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_date_joined', models.DateField()),
                ('user_profile_image', models.ImageField(blank=True, null=True, upload_to='Bidbay1/static/Bidbay1/profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(max_length=1500)),
                ('item_auction_type', models.CharField(max_length=20)),
                ('item_starting_price', models.IntegerField()),
                ('item_current_price', models.IntegerField()),
                ('item_final_price', models.IntegerField()),
                ('item_upload_date', models.DateTimeField()),
                ('item_category', models.CharField(max_length=20)),
                ('item_expiry_date', models.DateTimeField()),
                ('item_buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bought', to='Bidbay1.userdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_uploaded', to='Bidbay1.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='Bidbay1/static/Bidbay1/product_images')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bidbay1.items')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bidbay1.userdetails')),
            ],
        ),
    ]
