# Generated by Django 5.0.4 on 2024-07-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bidbay1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_current_price',
        ),
    ]
