# Generated by Django 5.1.6 on 2025-02-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidbay1', '0004_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid')], default='Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bidbay1.userdetails'),
        ),
    ]
