# Generated by Django 5.1.6 on 2025-02-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidbay1', '0005_items_item_payment_status_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Processing', 'Processing')], default='Processing', max_length=100),
        ),
    ]
