# Generated by Django 5.1.6 on 2025-02-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidbay1', '0006_alter_items_item_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_bids',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bidbay1.items')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bidbay1.userdetails')),
            ],
        ),
    ]
